version: '3.5'
 
services:

  postgres:
    image: postgres_dp1
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-WakeDP1}
      PGDATA: /data/postgres
    volumes:
       - postgres_data:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
   
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:4.28
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-waketeam@wake.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-WakeDP1}
    volumes:
       - pgadmin:/root/.pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped
 
networks:
  default:
    driver: bridge
 
volumes:
    postgres_data:
    pgadmin: